Fix test in CI

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -14,7 +14,7 @@ jobs:
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
-      
+
       - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
@@ -23,18 +23,26 @@ jobs:
 
       - name: build
         shell: bash
+        env:
+          DOCKER_BUILDKIT: 1
         run: |
-          docker pull rmind/nxsearch-svc:ci || echo "Can't download" \
-          docker build \
+          docker pull rmind/nxsearch-svc:ci || echo "Can't download"
+          docker buildx build \
             --tag rmind/nxsearch-svc:ci \
+            --cache-from rmind/nxsearch-svc:ci \
+            --build-arg BUILDKIT_INLINE_CACHE=1 \
             --target nxsearch-svc \
+            --output type=docker \
             -f compose/svc.Dockerfile .
 
       - name: Integration test
         shell: bash
         run: |
-          docker run -d --name test-svc -p "127.0.0.1:8000:8000" rmind/nxsearch-svc:ci && \
-          sh ./tools/svc_test.sh \
+          docker run -d \
+            --name test-svc \
+            -p "127.0.0.1:8000:8000" \
+            rmind/nxsearch-svc:ci
+          sh ./tools/svc_test.sh
           docker rm -f test-svc
 
       - name: push
